"""
Pydantic models for evidence curation pipeline.

These models define the structure for:
- Evidence manifest (captures from Witness agent)
- Review results (from Evidence Reviewer)
- Crop metadata (from Image Editor)
"""

from pathlib import Path
from typing import Literal, Optional

from pydantic import BaseModel, Field


class CropBox(BaseModel):
    """
    Represents a rectangular crop region in an image.
    Used for both cropping and highlighting text regions.
    """

    x: int = Field(description="Left edge position in pixels")
    y: int = Field(description="Top edge position in pixels")
    width: int = Field(description="Width of the crop region in pixels")
    height: int = Field(description="Height of the crop region in pixels")


class VariantReview(BaseModel):
    """
    Review result for a single screenshot variant.
    Generated by the Evidence Reviewer using vision LLM analysis.
    """

    score: int = Field(
        ge=0,
        le=10,
        description="Quality score from 0-10 based on clarity, relevance, readability",
    )
    keep: bool = Field(description="Whether this variant should be kept for curation")
    reason: str = Field(description="Explanation for the score and keep decision")
    is_blank: bool = Field(
        default=False, description="Whether the image is mostly blank/empty"
    )
    has_anchor_text: bool = Field(
        default=True, description="Whether the anchor text is visible in the image"
    )
    text_readable: bool = Field(
        default=True, description="Whether text in the image is clearly readable"
    )


class CaptureFiles(BaseModel):
    """
    File paths for the 5 screenshot variants captured by Witness agent.
    All paths are relative to the evidence/ folder.
    """

    element_padded: Optional[str] = Field(
        default=None, description="Element with 20px padding"
    )
    element_tight: Optional[str] = Field(
        default=None, description="Element tight crop, no padding"
    )
    context: Optional[str] = Field(
        default=None, description="Parent container with padding"
    )
    viewport: Optional[str] = Field(default=None, description="Current viewport")
    fullpage: Optional[str] = Field(default=None, description="Full page screenshot")


VariantType = Literal[
    "element_padded", "element_tight", "context", "viewport", "fullpage"
]


class CuratedEvidence(BaseModel):
    """
    Result of the Image Editor's curation process.
    Contains the final cropped image and its metadata.
    """

    file: str = Field(description="Path to curated image, relative to evidence/")
    source_variant: VariantType = Field(
        description="Which variant was used as the source"
    )
    crop: Optional[CropBox] = Field(
        default=None, description="Crop coordinates applied (if any)"
    )
    dimensions: Optional[dict[str, int]] = Field(
        default=None, description="Final image dimensions {width, height}"
    )


class EvidenceCapture(BaseModel):
    """
    A single evidence capture with its files, review results, and curated output.
    This is the main data structure tracked in manifest.json.
    """

    id: str = Field(description="Unique identifier for this capture (e.g., techspot_001)")
    url: str = Field(description="Source URL where the evidence was captured")
    description: str = Field(description="What this evidence shows")
    anchor_text: str = Field(
        description="Key text that should be visible in the screenshot"
    )
    files: CaptureFiles = Field(
        default_factory=CaptureFiles, description="Screenshot variant file paths"
    )

    # Added by Evidence Reviewer
    review: Optional[dict[str, VariantReview]] = Field(
        default=None,
        description="Review results for each variant (keyed by variant type)",
    )
    best_variant: Optional[VariantType] = Field(
        default=None, description="The highest scoring variant"
    )

    # Added by Image Editor
    curated: Optional[CuratedEvidence] = Field(
        default=None, description="Curated/cropped version of the best variant"
    )

    # Added by Highlighter (future)
    highlight_box: Optional[CropBox] = Field(
        default=None, description="Coordinates for text highlighting overlay"
    )


class EvidenceManifest(BaseModel):
    """
    The complete evidence manifest for a project.
    Stored as projects/{id}/evidence/manifest.json.
    """

    project_id: Optional[str] = Field(
        default=None, description="Project identifier"
    )
    captures: list[EvidenceCapture] = Field(
        default_factory=list, description="All evidence captures for this project"
    )
    reviewed: bool = Field(
        default=False, description="Whether evidence has been reviewed"
    )
    curated: bool = Field(
        default=False, description="Whether evidence has been curated/cropped"
    )

    def get_capture(self, capture_id: str) -> Optional[EvidenceCapture]:
        """Find a capture by its ID."""
        for capture in self.captures:
            if capture.id == capture_id:
                return capture
        return None

    def get_kept_captures(self) -> list[EvidenceCapture]:
        """Return captures that have at least one kept variant."""
        kept = []
        for capture in self.captures:
            if capture.review:
                if any(r.keep for r in capture.review.values()):
                    kept.append(capture)
        return kept

    @classmethod
    def load(cls, evidence_dir: Path) -> "EvidenceManifest":
        """Load manifest from evidence directory."""
        manifest_path = evidence_dir / "manifest.json"
        if manifest_path.exists():
            return cls.model_validate_json(manifest_path.read_text())
        return cls()

    def save(self, evidence_dir: Path) -> None:
        """Save manifest to evidence directory."""
        manifest_path = evidence_dir / "manifest.json"
        manifest_path.write_text(self.model_dump_json(indent=2))
